---
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '{{ cookiecutter.python_version }}'
  jobs:
    post_create_environment:
      - python -m pip install poetry
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs

sphinx:
  configuration: docs/source/conf.py
...
